#version 450
#define GLSLIFY 1

layout (local_size_x = 256) in;

struct GlobalLocal
{
    int global;
    int local;
};

layout(set = 0, binding = 0) buffer StorageBuffer
{
    GlobalLocal data[];
} block;

void main()
{
    //grab global ID
	uint gID = gl_GlobalInvocationID.x;
    uint lID = gl_LocalInvocationID.x;
    block.data[gID].global = int(gID);
    block.data[gID].local = int(lID);
    //
    block.data[0].global = int(gID);
}