// Module Version 10000
// Generated by (magic number): 8000a
// Id's are bound by 710

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint GLCompute 4  "main" 239
                              ExecutionMode 4 LocalSize 32 32 1
                              Source GLSL 450
                              SourceExtension  "GL_GOOGLE_cpp_style_line_directive"
                              SourceExtension  "GL_GOOGLE_include_directive"
                              Name 4  "main"
                              Name 6  "SetupWorld("
                              Name 10  "Ray"
                              MemberName 10(Ray) 0  "origin"
                              MemberName 10(Ray) 1  "direction"
                              Name 13  "Material"
                              MemberName 13(Material) 0  "type"
                              MemberName 13(Material) 1  "ptr"
                              Name 14  "Lambertian"
                              MemberName 14(Lambertian) 0  "albedo"
                              Name 15  "Sphere"
                              MemberName 15(Sphere) 0  "center"
                              MemberName 15(Sphere) 1  "radius"
                              MemberName 15(Sphere) 2  "mat"
                              MemberName 15(Sphere) 3  "lam"
                              Name 19  "World"
                              MemberName 19(World) 0  "object"
                              MemberName 19(World) 1  "count"
                              Name 24  "RayColor(struct-Ray-vf3-vf31;struct-World-struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311[10]-i11;"
                              Name 22  "r"
                              Name 23  "world"
                              Name 28  "HitRecord"
                              MemberName 28(HitRecord) 0  "p"
                              MemberName 28(HitRecord) 1  "normal"
                              MemberName 28(HitRecord) 2  "t"
                              MemberName 28(HitRecord) 3  "frontFace"
                              MemberName 28(HitRecord) 4  "mat"
                              MemberName 28(HitRecord) 5  "lam"
                              Name 37  "scatter(struct-Material-u1-u11;struct-Ray-vf3-vf31;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;struct-Ray-vf3-vf31;"
                              Name 32  "self"
                              Name 33  "r_in"
                              Name 34  "rec"
                              Name 35  "attenuation"
                              Name 36  "scattered"
                              Name 46  "scatter(struct-Lambertian-vf31;struct-Ray-vf3-vf31;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;struct-Ray-vf3-vf31;"
                              Name 41  "self"
                              Name 42  "r_in"
                              Name 43  "rec"
                              Name 44  "attenuation"
                              Name 45  "scattered"
                              Name 52  "Init(struct-Ray-vf3-vf31;vf3;vf3;"
                              Name 49  "self"
                              Name 50  "origin"
                              Name 51  "direction"
                              Name 58  "At(struct-Ray-vf3-vf31;f1;"
                              Name 56  "self"
                              Name 57  "t"
                              Name 65  "Init(struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;f1;"
                              Name 62  "self"
                              Name 63  "center"
                              Name 64  "radius"
                              Name 73  "Hit(struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311;struct-Ray-vf3-vf31;f1;f1;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;"
                              Name 68  "self"
                              Name 69  "r"
                              Name 70  "t_min"
                              Name 71  "t_max"
                              Name 72  "rec"
                              Name 75  "Camera"
                              MemberName 75(Camera) 0  "origin"
                              MemberName 75(Camera) 1  "horizontal"
                              MemberName 75(Camera) 2  "vertical"
                              MemberName 75(Camera) 3  "lowerLeftCorner"
                              MemberName 75(Camera) 4  "viewportHeight"
                              MemberName 75(Camera) 5  "viewportWidth"
                              MemberName 75(Camera) 6  "aspectRatio"
                              MemberName 75(Camera) 7  "focalLength"
                              Name 81  "GetRay(struct-Camera-vf3-vf3-vf3-vf3-f1-f1-f1-f11;f1;f1;"
                              Name 78  "self"
                              Name 79  "u"
                              Name 80  "v"
                              Name 87  "SetFaceNormal(struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;struct-Ray-vf3-vf31;vf3;"
                              Name 84  "self"
                              Name 85  "r"
                              Name 86  "outwardNormal"
                              Name 95  "Hit(struct-World-struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311[10]-i11;struct-Ray-vf3-vf31;f1;f1;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;"
                              Name 90  "self"
                              Name 91  "r"
                              Name 92  "t_min"
                              Name 93  "t_max"
                              Name 94  "rec"
                              Name 99  "BackgroundColor(struct-Ray-vf3-vf31;"
                              Name 98  "r"
                              Name 106  "WriteColor(i1;i1;vf3;"
                              Name 103  "x"
                              Name 104  "y"
                              Name 105  "color"
                              Name 109  "xor_shift_rand("
                              Name 116  "Seed(vu2;vu2;"
                              Name 114  "screenCoord"
                              Name 115  "screenSize"
                              Name 119  "Rand("
                              Name 123  "RandVec2("
                              Name 126  "RandVec3("
                              Name 128  "m"
                              Name 138  "lambertians"
                              Name 144  "world"
                              Name 148  "param"
                              Name 152  "param"
                              Name 153  "param"
                              Name 164  "param"
                              Name 167  "param"
                              Name 168  "param"
                              Name 176  "color"
                              Name 179  "next"
                              Name 181  "i"
                              Name 192  "rec"
                              Name 193  "param"
                              Name 195  "param"
                              Name 197  "param"
                              Name 198  "param"
                              Name 199  "param"
                              Name 205  "attenuation"
                              Name 206  "param"
                              Name 209  "param"
                              Name 211  "param"
                              Name 213  "param"
                              Name 214  "param"
                              Name 228  "param"
                              Name 239  "gl_GlobalInvocationID"
                              Name 241  "PushConstant"
                              MemberName 241(PushConstant) 0  "screenSize"
                              Name 243  ""
                              Name 248  "param"
                              Name 251  "param"
                              Name 275  "i"
                              Name 279  "j"
                              Name 283  "color"
                              Name 284  "sam"
                              Name 293  "v"
                              Name 307  "u"
                              Name 317  "r"
                              Name 318  "Camera"
                              MemberName 318(Camera) 0  "origin"
                              MemberName 318(Camera) 1  "horizontal"
                              MemberName 318(Camera) 2  "vertical"
                              MemberName 318(Camera) 3  "lowerLeftCorner"
                              MemberName 318(Camera) 4  "viewportHeight"
                              MemberName 318(Camera) 5  "viewportWidth"
                              MemberName 318(Camera) 6  "aspectRatio"
                              MemberName 318(Camera) 7  "focalLength"
                              Name 319  "CameraBuffer"
                              MemberName 319(CameraBuffer) 0  "camera"
                              Name 321  ""
                              Name 322  "param"
                              Name 346  "param"
                              Name 348  "param"
                              Name 351  "param"
                              Name 353  "param"
                              Name 364  "param"
                              Name 366  "param"
                              Name 368  "param"
                              Name 377  "param"
                              Name 381  "param"
                              Name 383  "param"
                              Name 385  "param"
                              Name 386  "param"
                              Name 395  "scatter_direction"
                              Name 400  "param"
                              Name 402  "param"
                              Name 405  "param"
                              Name 432  "oc"
                              Name 438  "a"
                              Name 444  "half_b"
                              Name 449  "c"
                              Name 459  "discriminant"
                              Name 472  "sqrtd"
                              Name 475  "root"
                              Name 509  "param"
                              Name 511  "param"
                              Name 516  "outwardNormal"
                              Name 526  "param"
                              Name 528  "param"
                              Name 530  "param"
                              Name 539  "r"
                              Name 555  "param"
                              Name 557  "param"
                              Name 560  "param"
                              Name 584  "hit_anything"
                              Name 585  "closest_so_far"
                              Name 587  "i"
                              Name 597  "o"
                              Name 601  "temp_rec"
                              Name 602  "param"
                              Name 604  "param"
                              Name 606  "param"
                              Name 608  "param"
                              Name 610  "param"
                              Name 623  "dir"
                              Name 626  "t"
                              Name 642  "TargetBuffer"
                              MemberName 642(TargetBuffer) 0  "pixels"
                              Name 644  "target"
                              Name 659  "state"
                              Name 706  ""
                              MemberName 706 0  "None"
                              MemberName 706 1  "Lambertian"
                              MemberName 706 2  "Metal"
                              MemberName 706 3  "Dielectrics"
                              Decorate 239(gl_GlobalInvocationID) BuiltIn GlobalInvocationId
                              MemberDecorate 241(PushConstant) 0 Offset 0
                              Decorate 241(PushConstant) Block
                              MemberDecorate 318(Camera) 0 Offset 0
                              MemberDecorate 318(Camera) 1 Offset 16
                              MemberDecorate 318(Camera) 2 Offset 32
                              MemberDecorate 318(Camera) 3 Offset 48
                              MemberDecorate 318(Camera) 4 Offset 60
                              MemberDecorate 318(Camera) 5 Offset 64
                              MemberDecorate 318(Camera) 6 Offset 68
                              MemberDecorate 318(Camera) 7 Offset 72
                              MemberDecorate 319(CameraBuffer) 0 Offset 0
                              Decorate 319(CameraBuffer) Block
                              Decorate 321 DescriptorSet 0
                              Decorate 321 Binding 1
                              Decorate 641 ArrayStride 16
                              MemberDecorate 642(TargetBuffer) 0 Offset 0
                              Decorate 642(TargetBuffer) BufferBlock
                              Decorate 644(target) DescriptorSet 0
                              Decorate 644(target) Binding 0
                              Decorate 705 BuiltIn WorkgroupSize
               2:             TypeVoid
               3:             TypeFunction 2
               8:             TypeFloat 32
               9:             TypeVector 8(float) 3
         10(Ray):             TypeStruct 9(fvec3) 9(fvec3)
              11:             TypePointer Function 10(Ray)
              12:             TypeInt 32 0
    13(Material):             TypeStruct 12(int) 12(int)
  14(Lambertian):             TypeStruct 9(fvec3)
      15(Sphere):             TypeStruct 9(fvec3) 8(float) 13(Material) 14(Lambertian)
              16:     12(int) Constant 10
              17:             TypeArray 15(Sphere) 16
              18:             TypeInt 32 1
       19(World):             TypeStruct 17 18(int)
              20:             TypePointer Function 19(World)
              21:             TypeFunction 9(fvec3) 11(ptr) 20(ptr)
              26:             TypePointer Function 13(Material)
              27:             TypeBool
   28(HitRecord):             TypeStruct 9(fvec3) 9(fvec3) 8(float) 27(bool) 13(Material) 14(Lambertian)
              29:             TypePointer Function 28(HitRecord)
              30:             TypePointer Function 9(fvec3)
              31:             TypeFunction 27(bool) 26(ptr) 11(ptr) 29(ptr) 30(ptr) 11(ptr)
              39:             TypePointer Function 14(Lambertian)
              40:             TypeFunction 27(bool) 39(ptr) 11(ptr) 29(ptr) 30(ptr) 11(ptr)
              48:             TypeFunction 2 11(ptr) 30(ptr) 30(ptr)
              54:             TypePointer Function 8(float)
              55:             TypeFunction 9(fvec3) 11(ptr) 54(ptr)
              60:             TypePointer Function 15(Sphere)
              61:             TypeFunction 2 60(ptr) 30(ptr) 54(ptr)
              67:             TypeFunction 27(bool) 60(ptr) 11(ptr) 54(ptr) 54(ptr) 29(ptr)
      75(Camera):             TypeStruct 9(fvec3) 9(fvec3) 9(fvec3) 9(fvec3) 8(float) 8(float) 8(float) 8(float)
              76:             TypePointer Function 75(Camera)
              77:             TypeFunction 10(Ray) 76(ptr) 54(ptr) 54(ptr)
              83:             TypeFunction 2 29(ptr) 11(ptr) 30(ptr)
              89:             TypeFunction 27(bool) 20(ptr) 11(ptr) 54(ptr) 54(ptr) 29(ptr)
              97:             TypeFunction 9(fvec3) 11(ptr)
             101:             TypePointer Function 18(int)
             102:             TypeFunction 2 101(ptr) 101(ptr) 30(ptr)
             108:             TypeFunction 12(int)
             111:             TypeVector 12(int) 2
             112:             TypePointer Function 111(ivec2)
             113:             TypeFunction 2 112(ptr) 112(ptr)
             118:             TypeFunction 8(float)
             121:             TypeVector 8(float) 2
             122:             TypeFunction 121(fvec2)
             125:             TypeFunction 9(fvec3)
             129:     18(int) Constant 0
             130:     12(int) Constant 1
             131:             TypePointer Function 12(int)
             133:     18(int) Constant 1
             134:     12(int) Constant 0
             136:             TypeArray 14(Lambertian) 130
             137:             TypePointer Private 136
138(lambertians):    137(ptr) Variable Private
             139:    8(float) Constant 1056964608
             140:    9(fvec3) ConstantComposite 139 139 139
             141:             TypePointer Private 9(fvec3)
             143:             TypePointer Private 19(World)
      144(world):    143(ptr) Variable Private
             145:    8(float) Constant 0
             146:    8(float) Constant 3212836864
             147:    9(fvec3) ConstantComposite 145 145 146
             149:             TypePointer Private 15(Sphere)
             157:     18(int) Constant 2
             159:             TypePointer Private 13(Material)
             161:    8(float) Constant 3267952640
             162:    9(fvec3) ConstantComposite 145 161 146
             163:    8(float) Constant 1120403456
             174:             TypePointer Private 18(int)
             177:    8(float) Constant 1065353216
             178:    9(fvec3) ConstantComposite 177 177 177
             188:     18(int) Constant 800
             190:    8(float) Constant 981668463
             191:    8(float) Constant 1176256512
             204:     18(int) Constant 4
             224:    9(fvec3) ConstantComposite 145 145 145
             237:             TypeVector 12(int) 3
             238:             TypePointer Input 237(ivec3)
239(gl_GlobalInvocationID):    238(ptr) Variable Input
             240:             TypeVector 18(int) 2
241(PushConstant):             TypeStruct 240(ivec2)
             242:             TypePointer PushConstant 241(PushConstant)
             243:    242(ptr) Variable PushConstant
             244:             TypePointer PushConstant 240(ivec2)
             254:             TypePointer Input 12(int)
             257:             TypePointer PushConstant 18(int)
             291:     18(int) Constant 200
     318(Camera):             TypeStruct 9(fvec3) 9(fvec3) 9(fvec3) 9(fvec3) 8(float) 8(float) 8(float) 8(float)
319(CameraBuffer):             TypeStruct 318(Camera)
             320:             TypePointer Uniform 319(CameraBuffer)
             321:    320(ptr) Variable Uniform
             323:             TypePointer Uniform 318(Camera)
             333:     18(int) Constant 3
             338:     18(int) Constant 5
             341:     18(int) Constant 6
             344:     18(int) Constant 7
             360:    8(float) Constant 1128792064
             378:             TypePointer Private 14(Lambertian)
             392:    27(bool) ConstantFalse
             411:    27(bool) ConstantTrue
             571:             TypePointer Function 27(bool)
             631:    8(float) Constant 1060320051
             632:    9(fvec3) ConstantComposite 139 631 177
             640:             TypeVector 8(float) 4
             641:             TypeRuntimeArray 640(fvec4)
642(TargetBuffer):             TypeStruct 641
             643:             TypePointer Uniform 642(TargetBuffer)
     644(target):    643(ptr) Variable Uniform
             656:             TypePointer Uniform 640(fvec4)
             658:             TypePointer Private 12(int)
      659(state):    658(ptr) Variable Private
             661:     18(int) Constant 13
             666:     18(int) Constant 17
             687:    8(float) Constant 796917760
             703:     18(int) Constant 32
             704:     12(int) Constant 32
             705:  237(ivec3) ConstantComposite 704 704 130
             706:             TypeStruct 12(int) 12(int) 12(int) 12(int)
             707:     12(int) Constant 2
             708:     12(int) Constant 4
             709: 706(struct) ConstantComposite 134 130 707 708
         4(main):           2 Function None 3
               5:             Label
      248(param):    112(ptr) Variable Function
      251(param):    112(ptr) Variable Function
          275(i):    101(ptr) Variable Function
          279(j):    101(ptr) Variable Function
      283(color):     30(ptr) Variable Function
        284(sam):    101(ptr) Variable Function
          293(v):     54(ptr) Variable Function
          307(u):     54(ptr) Variable Function
          317(r):     11(ptr) Variable Function
      322(param):     76(ptr) Variable Function
      346(param):     54(ptr) Variable Function
      348(param):     54(ptr) Variable Function
      351(param):     11(ptr) Variable Function
      353(param):     20(ptr) Variable Function
      364(param):    101(ptr) Variable Function
      366(param):    101(ptr) Variable Function
      368(param):     30(ptr) Variable Function
             245:    244(ptr) AccessChain 243 129
             246:  240(ivec2) Load 245
             247:  111(ivec2) Bitcast 246
             249:  237(ivec3) Load 239(gl_GlobalInvocationID)
             250:  111(ivec2) VectorShuffle 249 249 0 1
                              Store 248(param) 250
                              Store 251(param) 247
             252:           2 FunctionCall 116(Seed(vu2;vu2;) 248(param) 251(param)
             253:           2 FunctionCall 6(SetupWorld()
             255:    254(ptr) AccessChain 239(gl_GlobalInvocationID) 134
             256:     12(int) Load 255
             258:    257(ptr) AccessChain 243 129 134
             259:     18(int) Load 258
             260:     12(int) Bitcast 259
             261:    27(bool) UGreaterThanEqual 256 260
             262:    27(bool) LogicalNot 261
                              SelectionMerge 264 None
                              BranchConditional 262 263 264
             263:               Label
             265:    254(ptr)   AccessChain 239(gl_GlobalInvocationID) 130
             266:     12(int)   Load 265
             267:    257(ptr)   AccessChain 243 129 130
             268:     18(int)   Load 267
             269:     12(int)   Bitcast 268
             270:    27(bool)   UGreaterThanEqual 266 269
                                Branch 264
             264:             Label
             271:    27(bool) Phi 261 5 270 263
                              SelectionMerge 273 None
                              BranchConditional 271 272 273
             272:               Label
                                Return
             273:             Label
             276:    254(ptr) AccessChain 239(gl_GlobalInvocationID) 134
             277:     12(int) Load 276
             278:     18(int) Bitcast 277
                              Store 275(i) 278
             280:    254(ptr) AccessChain 239(gl_GlobalInvocationID) 130
             281:     12(int) Load 280
             282:     18(int) Bitcast 281
                              Store 279(j) 282
                              Store 283(color) 224
                              Store 284(sam) 129
                              Branch 285
             285:             Label
                              LoopMerge 287 288 None
                              Branch 289
             289:             Label
             290:     18(int) Load 284(sam)
             292:    27(bool) SLessThan 290 291
                              BranchConditional 292 286 287
             286:               Label
             294:    257(ptr)   AccessChain 243 129 130
             295:     18(int)   Load 294
             296:     18(int)   Load 279(j)
             297:     18(int)   ISub 295 296
             298:     18(int)   ISub 297 133
             299:    8(float)   ConvertSToF 298
             300:    8(float)   FunctionCall 119(Rand()
             301:    8(float)   FAdd 299 300
             302:    257(ptr)   AccessChain 243 129 130
             303:     18(int)   Load 302
             304:     18(int)   ISub 303 133
             305:    8(float)   ConvertSToF 304
             306:    8(float)   FDiv 301 305
                                Store 293(v) 306
             308:     18(int)   Load 275(i)
             309:    8(float)   ConvertSToF 308
             310:    8(float)   FunctionCall 119(Rand()
             311:    8(float)   FAdd 309 310
             312:    257(ptr)   AccessChain 243 129 134
             313:     18(int)   Load 312
             314:     18(int)   ISub 313 133
             315:    8(float)   ConvertSToF 314
             316:    8(float)   FDiv 311 315
                                Store 307(u) 316
             324:    323(ptr)   AccessChain 321 129
             325: 318(Camera)   Load 324
             326:    9(fvec3)   CompositeExtract 325 0
             327:     30(ptr)   AccessChain 322(param) 129
                                Store 327 326
             328:    9(fvec3)   CompositeExtract 325 1
             329:     30(ptr)   AccessChain 322(param) 133
                                Store 329 328
             330:    9(fvec3)   CompositeExtract 325 2
             331:     30(ptr)   AccessChain 322(param) 157
                                Store 331 330
             332:    9(fvec3)   CompositeExtract 325 3
             334:     30(ptr)   AccessChain 322(param) 333
                                Store 334 332
             335:    8(float)   CompositeExtract 325 4
             336:     54(ptr)   AccessChain 322(param) 204
                                Store 336 335
             337:    8(float)   CompositeExtract 325 5
             339:     54(ptr)   AccessChain 322(param) 338
                                Store 339 337
             340:    8(float)   CompositeExtract 325 6
             342:     54(ptr)   AccessChain 322(param) 341
                                Store 342 340
             343:    8(float)   CompositeExtract 325 7
             345:     54(ptr)   AccessChain 322(param) 344
                                Store 345 343
             347:    8(float)   Load 307(u)
                                Store 346(param) 347
             349:    8(float)   Load 293(v)
                                Store 348(param) 349
             350:     10(Ray)   FunctionCall 81(GetRay(struct-Camera-vf3-vf3-vf3-vf3-f1-f1-f1-f11;f1;f1;) 322(param) 346(param) 348(param)
                                Store 317(r) 350
             352:     10(Ray)   Load 317(r)
                                Store 351(param) 352
             354:   19(World)   Load 144(world)
                                Store 353(param) 354
             355:    9(fvec3)   FunctionCall 24(RayColor(struct-Ray-vf3-vf31;struct-World-struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311[10]-i11;) 351(param) 353(param)
             356:    9(fvec3)   Load 283(color)
             357:    9(fvec3)   FAdd 356 355
                                Store 283(color) 357
                                Branch 288
             288:               Label
             358:     18(int)   Load 284(sam)
             359:     18(int)   IAdd 358 133
                                Store 284(sam) 359
                                Branch 285
             287:             Label
             361:    9(fvec3) Load 283(color)
             362:    9(fvec3) CompositeConstruct 360 360 360
             363:    9(fvec3) FDiv 361 362
                              Store 283(color) 363
             365:     18(int) Load 275(i)
                              Store 364(param) 365
             367:     18(int) Load 279(j)
                              Store 366(param) 367
             369:    9(fvec3) Load 283(color)
                              Store 368(param) 369
             370:           2 FunctionCall 106(WriteColor(i1;i1;vf3;) 364(param) 366(param) 368(param)
                              Return
                              FunctionEnd
  6(SetupWorld():           2 Function None 3
               7:             Label
          128(m):     26(ptr) Variable Function
      148(param):     60(ptr) Variable Function
      152(param):     30(ptr) Variable Function
      153(param):     54(ptr) Variable Function
      164(param):     60(ptr) Variable Function
      167(param):     30(ptr) Variable Function
      168(param):     54(ptr) Variable Function
             132:    131(ptr) AccessChain 128(m) 129
                              Store 132 130
             135:    131(ptr) AccessChain 128(m) 133
                              Store 135 134
             142:    141(ptr) AccessChain 138(lambertians) 129 129
                              Store 142 140
             150:    149(ptr) AccessChain 144(world) 129 129
             151:  15(Sphere) Load 150
                              Store 148(param) 151
                              Store 152(param) 147
                              Store 153(param) 139
             154:           2 FunctionCall 65(Init(struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;f1;) 148(param) 152(param) 153(param)
             155:  15(Sphere) Load 148(param)
             156:    149(ptr) AccessChain 144(world) 129 129
                              Store 156 155
             158:13(Material) Load 128(m)
             160:    159(ptr) AccessChain 144(world) 129 129 157
                              Store 160 158
             165:    149(ptr) AccessChain 144(world) 129 133
             166:  15(Sphere) Load 165
                              Store 164(param) 166
                              Store 167(param) 162
                              Store 168(param) 163
             169:           2 FunctionCall 65(Init(struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;f1;) 164(param) 167(param) 168(param)
             170:  15(Sphere) Load 164(param)
             171:    149(ptr) AccessChain 144(world) 129 133
                              Store 171 170
             172:13(Material) Load 128(m)
             173:    159(ptr) AccessChain 144(world) 129 133 157
                              Store 173 172
             175:    174(ptr) AccessChain 144(world) 133
                              Store 175 157
                              Return
                              FunctionEnd
24(RayColor(struct-Ray-vf3-vf31;struct-World-struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311[10]-i11;):    9(fvec3) Function None 21
           22(r):     11(ptr) FunctionParameter
       23(world):     20(ptr) FunctionParameter
              25:             Label
      176(color):     30(ptr) Variable Function
       179(next):     11(ptr) Variable Function
          181(i):    101(ptr) Variable Function
        192(rec):     29(ptr) Variable Function
      193(param):     20(ptr) Variable Function
      195(param):     11(ptr) Variable Function
      197(param):     54(ptr) Variable Function
      198(param):     54(ptr) Variable Function
      199(param):     29(ptr) Variable Function
205(attenuation):     30(ptr) Variable Function
      206(param):     26(ptr) Variable Function
      209(param):     11(ptr) Variable Function
      211(param):     29(ptr) Variable Function
      213(param):     30(ptr) Variable Function
      214(param):     11(ptr) Variable Function
      228(param):     11(ptr) Variable Function
                              Store 176(color) 178
             180:     10(Ray) Load 22(r)
                              Store 179(next) 180
                              Store 181(i) 129
                              Branch 182
             182:             Label
                              LoopMerge 184 185 None
                              Branch 186
             186:             Label
             187:     18(int) Load 181(i)
             189:    27(bool) SLessThan 187 188
                              BranchConditional 189 183 184
             183:               Label
             194:   19(World)   Load 23(world)
                                Store 193(param) 194
             196:     10(Ray)   Load 179(next)
                                Store 195(param) 196
                                Store 197(param) 190
                                Store 198(param) 191
             200:    27(bool)   FunctionCall 95(Hit(struct-World-struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311[10]-i11;struct-Ray-vf3-vf31;f1;f1;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;) 193(param) 195(param) 197(param) 198(param) 199(param)
             201:28(HitRecord)   Load 199(param)
                                Store 192(rec) 201
                                SelectionMerge 203 None
                                BranchConditional 200 202 226
             202:                 Label
             207:     26(ptr)     AccessChain 192(rec) 204
             208:13(Material)     Load 207
                                  Store 206(param) 208
             210:     10(Ray)     Load 22(r)
                                  Store 209(param) 210
             212:28(HitRecord)     Load 192(rec)
                                  Store 211(param) 212
             215:    27(bool)     FunctionCall 37(scatter(struct-Material-u1-u11;struct-Ray-vf3-vf31;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;struct-Ray-vf3-vf31;) 206(param) 209(param) 211(param) 213(param) 214(param)
             216:    9(fvec3)     Load 213(param)
                                  Store 205(attenuation) 216
             217:     10(Ray)     Load 214(param)
                                  Store 179(next) 217
                                  SelectionMerge 219 None
                                  BranchConditional 215 218 223
             218:                   Label
             220:    9(fvec3)       Load 205(attenuation)
             221:    9(fvec3)       Load 176(color)
             222:    9(fvec3)       FMul 221 220
                                    Store 176(color) 222
                                    Branch 219
             223:                   Label
                                    ReturnValue 224
             219:                 Label
                                  Branch 203
             226:                 Label
             227:    9(fvec3)     Load 176(color)
             229:     10(Ray)     Load 179(next)
                                  Store 228(param) 229
             230:    9(fvec3)     FunctionCall 99(BackgroundColor(struct-Ray-vf3-vf31;) 228(param)
             231:    9(fvec3)     FMul 227 230
                                  ReturnValue 231
             203:               Label
                                Branch 185
             185:               Label
             233:     18(int)   Load 181(i)
             234:     18(int)   IAdd 233 133
                                Store 181(i) 234
                                Branch 182
             184:             Label
                              ReturnValue 224
                              FunctionEnd
37(scatter(struct-Material-u1-u11;struct-Ray-vf3-vf31;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;struct-Ray-vf3-vf31;):    27(bool) Function None 31
        32(self):     26(ptr) FunctionParameter
        33(r_in):     11(ptr) FunctionParameter
         34(rec):     29(ptr) FunctionParameter
 35(attenuation):     30(ptr) FunctionParameter
   36(scattered):     11(ptr) FunctionParameter
              38:             Label
      377(param):     39(ptr) Variable Function
      381(param):     11(ptr) Variable Function
      383(param):     29(ptr) Variable Function
      385(param):     30(ptr) Variable Function
      386(param):     11(ptr) Variable Function
             371:    131(ptr) AccessChain 32(self) 129
             372:     12(int) Load 371
                              SelectionMerge 374 None
                              Switch 372 374 
                                     case 1: 373
             373:               Label
             375:    131(ptr)   AccessChain 32(self) 133
             376:     12(int)   Load 375
             379:    378(ptr)   AccessChain 138(lambertians) 376
             380:14(Lambertian)   Load 379
                                Store 377(param) 380
             382:     10(Ray)   Load 33(r_in)
                                Store 381(param) 382
             384:28(HitRecord)   Load 34(rec)
                                Store 383(param) 384
             387:    27(bool)   FunctionCall 46(scatter(struct-Lambertian-vf31;struct-Ray-vf3-vf31;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;struct-Ray-vf3-vf31;) 377(param) 381(param) 383(param) 385(param) 386(param)
             388:    9(fvec3)   Load 385(param)
                                Store 35(attenuation) 388
             389:     10(Ray)   Load 386(param)
                                Store 36(scattered) 389
                                ReturnValue 387
             374:             Label
                              ReturnValue 392
                              FunctionEnd
46(scatter(struct-Lambertian-vf31;struct-Ray-vf3-vf31;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;struct-Ray-vf3-vf31;):    27(bool) Function None 40
        41(self):     39(ptr) FunctionParameter
        42(r_in):     11(ptr) FunctionParameter
         43(rec):     29(ptr) FunctionParameter
 44(attenuation):     30(ptr) FunctionParameter
   45(scattered):     11(ptr) FunctionParameter
              47:             Label
395(scatter_direction):     30(ptr) Variable Function
      400(param):     11(ptr) Variable Function
      402(param):     30(ptr) Variable Function
      405(param):     30(ptr) Variable Function
             396:     30(ptr) AccessChain 43(rec) 133
             397:    9(fvec3) Load 396
             398:    9(fvec3) FunctionCall 126(RandVec3()
             399:    9(fvec3) FAdd 397 398
                              Store 395(scatter_direction) 399
             401:     10(Ray) Load 45(scattered)
                              Store 400(param) 401
             403:     30(ptr) AccessChain 43(rec) 129
             404:    9(fvec3) Load 403
                              Store 402(param) 404
             406:    9(fvec3) Load 395(scatter_direction)
                              Store 405(param) 406
             407:           2 FunctionCall 52(Init(struct-Ray-vf3-vf31;vf3;vf3;) 400(param) 402(param) 405(param)
             408:     10(Ray) Load 400(param)
                              Store 45(scattered) 408
             409:     30(ptr) AccessChain 41(self) 129
             410:    9(fvec3) Load 409
                              Store 44(attenuation) 410
                              ReturnValue 411
                              FunctionEnd
52(Init(struct-Ray-vf3-vf31;vf3;vf3;):           2 Function None 48
        49(self):     11(ptr) FunctionParameter
      50(origin):     30(ptr) FunctionParameter
   51(direction):     30(ptr) FunctionParameter
              53:             Label
             414:    9(fvec3) Load 50(origin)
             415:     30(ptr) AccessChain 49(self) 129
                              Store 415 414
             416:    9(fvec3) Load 51(direction)
             417:    9(fvec3) ExtInst 1(GLSL.std.450) 69(Normalize) 416
             418:     30(ptr) AccessChain 49(self) 133
                              Store 418 417
                              Return
                              FunctionEnd
58(At(struct-Ray-vf3-vf31;f1;):    9(fvec3) Function None 55
        56(self):     11(ptr) FunctionParameter
           57(t):     54(ptr) FunctionParameter
              59:             Label
             419:     30(ptr) AccessChain 56(self) 129
             420:    9(fvec3) Load 419
             421:     30(ptr) AccessChain 56(self) 133
             422:    9(fvec3) Load 421
             423:    8(float) Load 57(t)
             424:    9(fvec3) VectorTimesScalar 422 423
             425:    9(fvec3) FAdd 420 424
                              ReturnValue 425
                              FunctionEnd
65(Init(struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311;vf3;f1;):           2 Function None 61
        62(self):     60(ptr) FunctionParameter
      63(center):     30(ptr) FunctionParameter
      64(radius):     54(ptr) FunctionParameter
              66:             Label
             428:    9(fvec3) Load 63(center)
             429:     30(ptr) AccessChain 62(self) 129
                              Store 429 428
             430:    8(float) Load 64(radius)
             431:     54(ptr) AccessChain 62(self) 133
                              Store 431 430
                              Return
                              FunctionEnd
73(Hit(struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311;struct-Ray-vf3-vf31;f1;f1;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;):    27(bool) Function None 67
        68(self):     60(ptr) FunctionParameter
           69(r):     11(ptr) FunctionParameter
       70(t_min):     54(ptr) FunctionParameter
       71(t_max):     54(ptr) FunctionParameter
         72(rec):     29(ptr) FunctionParameter
              74:             Label
         432(oc):     30(ptr) Variable Function
          438(a):     54(ptr) Variable Function
     444(half_b):     54(ptr) Variable Function
          449(c):     54(ptr) Variable Function
459(discriminant):     54(ptr) Variable Function
      472(sqrtd):     54(ptr) Variable Function
       475(root):     54(ptr) Variable Function
      509(param):     11(ptr) Variable Function
      511(param):     54(ptr) Variable Function
516(outwardNormal):     30(ptr) Variable Function
      526(param):     29(ptr) Variable Function
      528(param):     11(ptr) Variable Function
      530(param):     30(ptr) Variable Function
             433:     30(ptr) AccessChain 69(r) 129
             434:    9(fvec3) Load 433
             435:     30(ptr) AccessChain 68(self) 129
             436:    9(fvec3) Load 435
             437:    9(fvec3) FSub 434 436
                              Store 432(oc) 437
             439:     30(ptr) AccessChain 69(r) 133
             440:    9(fvec3) Load 439
             441:     30(ptr) AccessChain 69(r) 133
             442:    9(fvec3) Load 441
             443:    8(float) Dot 440 442
                              Store 438(a) 443
             445:    9(fvec3) Load 432(oc)
             446:     30(ptr) AccessChain 69(r) 133
             447:    9(fvec3) Load 446
             448:    8(float) Dot 445 447
                              Store 444(half_b) 448
             450:    9(fvec3) Load 432(oc)
             451:    9(fvec3) Load 432(oc)
             452:    8(float) Dot 450 451
             453:     54(ptr) AccessChain 68(self) 133
             454:    8(float) Load 453
             455:     54(ptr) AccessChain 68(self) 133
             456:    8(float) Load 455
             457:    8(float) FMul 454 456
             458:    8(float) FSub 452 457
                              Store 449(c) 458
             460:    8(float) Load 444(half_b)
             461:    8(float) Load 444(half_b)
             462:    8(float) FMul 460 461
             463:    8(float) Load 438(a)
             464:    8(float) Load 449(c)
             465:    8(float) FMul 463 464
             466:    8(float) FSub 462 465
                              Store 459(discriminant) 466
             467:    8(float) Load 459(discriminant)
             468:    27(bool) FOrdLessThan 467 145
                              SelectionMerge 470 None
                              BranchConditional 468 469 470
             469:               Label
                                ReturnValue 392
             470:             Label
             473:    8(float) Load 459(discriminant)
             474:    8(float) ExtInst 1(GLSL.std.450) 31(Sqrt) 473
                              Store 472(sqrtd) 474
             476:    8(float) Load 444(half_b)
             477:    8(float) FNegate 476
             478:    8(float) Load 472(sqrtd)
             479:    8(float) FSub 477 478
             480:    8(float) Load 438(a)
             481:    8(float) FDiv 479 480
                              Store 475(root) 481
             482:    8(float) Load 475(root)
             483:    8(float) Load 70(t_min)
             484:    27(bool) FOrdLessThan 482 483
             485:    8(float) Load 71(t_max)
             486:    8(float) Load 475(root)
             487:    27(bool) FOrdLessThan 485 486
             488:    27(bool) LogicalOr 484 487
                              SelectionMerge 490 None
                              BranchConditional 488 489 490
             489:               Label
             491:    8(float)   Load 444(half_b)
             492:    8(float)   FNegate 491
             493:    8(float)   Load 472(sqrtd)
             494:    8(float)   FAdd 492 493
             495:    8(float)   Load 438(a)
             496:    8(float)   FDiv 494 495
                                Store 475(root) 496
             497:    8(float)   Load 475(root)
             498:    8(float)   Load 70(t_min)
             499:    27(bool)   FOrdLessThan 497 498
             500:    8(float)   Load 71(t_max)
             501:    8(float)   Load 475(root)
             502:    27(bool)   FOrdLessThan 500 501
             503:    27(bool)   LogicalOr 499 502
                                SelectionMerge 505 None
                                BranchConditional 503 504 505
             504:                 Label
                                  ReturnValue 392
             505:               Label
                                Branch 490
             490:             Label
             507:    8(float) Load 475(root)
             508:     54(ptr) AccessChain 72(rec) 157
                              Store 508 507
             510:     10(Ray) Load 69(r)
                              Store 509(param) 510
             512:     54(ptr) AccessChain 72(rec) 157
             513:    8(float) Load 512
                              Store 511(param) 513
             514:    9(fvec3) FunctionCall 58(At(struct-Ray-vf3-vf31;f1;) 509(param) 511(param)
             515:     30(ptr) AccessChain 72(rec) 129
                              Store 515 514
             517:     30(ptr) AccessChain 72(rec) 129
             518:    9(fvec3) Load 517
             519:     30(ptr) AccessChain 68(self) 129
             520:    9(fvec3) Load 519
             521:    9(fvec3) FSub 518 520
             522:     54(ptr) AccessChain 68(self) 133
             523:    8(float) Load 522
             524:    9(fvec3) CompositeConstruct 523 523 523
             525:    9(fvec3) FDiv 521 524
                              Store 516(outwardNormal) 525
             527:28(HitRecord) Load 72(rec)
                              Store 526(param) 527
             529:     10(Ray) Load 69(r)
                              Store 528(param) 529
             531:    9(fvec3) Load 516(outwardNormal)
                              Store 530(param) 531
             532:           2 FunctionCall 87(SetFaceNormal(struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;struct-Ray-vf3-vf31;vf3;) 526(param) 528(param) 530(param)
             533:28(HitRecord) Load 526(param)
                              Store 72(rec) 533
             534:     26(ptr) AccessChain 68(self) 157
             535:13(Material) Load 534
             536:     26(ptr) AccessChain 72(rec) 204
                              Store 536 535
                              ReturnValue 411
                              FunctionEnd
81(GetRay(struct-Camera-vf3-vf3-vf3-vf3-f1-f1-f1-f11;f1;f1;):     10(Ray) Function None 77
        78(self):     76(ptr) FunctionParameter
           79(u):     54(ptr) FunctionParameter
           80(v):     54(ptr) FunctionParameter
              82:             Label
          539(r):     11(ptr) Variable Function
      555(param):     11(ptr) Variable Function
      557(param):     30(ptr) Variable Function
      560(param):     30(ptr) Variable Function
             540:     30(ptr) AccessChain 78(self) 333
             541:    9(fvec3) Load 540
             542:    8(float) Load 79(u)
             543:     30(ptr) AccessChain 78(self) 133
             544:    9(fvec3) Load 543
             545:    9(fvec3) VectorTimesScalar 544 542
             546:    9(fvec3) FAdd 541 545
             547:    8(float) Load 80(v)
             548:     30(ptr) AccessChain 78(self) 157
             549:    9(fvec3) Load 548
             550:    9(fvec3) VectorTimesScalar 549 547
             551:    9(fvec3) FAdd 546 550
             552:     30(ptr) AccessChain 78(self) 129
             553:    9(fvec3) Load 552
             554:    9(fvec3) FSub 551 553
             556:     10(Ray) Load 539(r)
                              Store 555(param) 556
             558:     30(ptr) AccessChain 78(self) 129
             559:    9(fvec3) Load 558
                              Store 557(param) 559
                              Store 560(param) 554
             561:           2 FunctionCall 52(Init(struct-Ray-vf3-vf31;vf3;vf3;) 555(param) 557(param) 560(param)
             562:     10(Ray) Load 555(param)
                              Store 539(r) 562
             563:     10(Ray) Load 539(r)
                              ReturnValue 563
                              FunctionEnd
87(SetFaceNormal(struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;struct-Ray-vf3-vf31;vf3;):           2 Function None 83
        84(self):     29(ptr) FunctionParameter
           85(r):     11(ptr) FunctionParameter
86(outwardNormal):     30(ptr) FunctionParameter
              88:             Label
             575:     30(ptr) Variable Function
             566:     30(ptr) AccessChain 85(r) 133
             567:    9(fvec3) Load 566
             568:    9(fvec3) Load 86(outwardNormal)
             569:    8(float) Dot 567 568
             570:    27(bool) FOrdLessThan 569 145
             572:    571(ptr) AccessChain 84(self) 333
                              Store 572 570
             573:    571(ptr) AccessChain 84(self) 333
             574:    27(bool) Load 573
                              SelectionMerge 577 None
                              BranchConditional 574 576 579
             576:               Label
             578:    9(fvec3)   Load 86(outwardNormal)
                                Store 575 578
                                Branch 577
             579:               Label
             580:    9(fvec3)   Load 86(outwardNormal)
             581:    9(fvec3)   FNegate 580
                                Store 575 581
                                Branch 577
             577:             Label
             582:    9(fvec3) Load 575
             583:     30(ptr) AccessChain 84(self) 133
                              Store 583 582
                              Return
                              FunctionEnd
95(Hit(struct-World-struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311[10]-i11;struct-Ray-vf3-vf31;f1;f1;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;):    27(bool) Function None 89
        90(self):     20(ptr) FunctionParameter
           91(r):     11(ptr) FunctionParameter
       92(t_min):     54(ptr) FunctionParameter
       93(t_max):     54(ptr) FunctionParameter
         94(rec):     29(ptr) FunctionParameter
              96:             Label
584(hit_anything):    571(ptr) Variable Function
585(closest_so_far):     54(ptr) Variable Function
          587(i):    101(ptr) Variable Function
          597(o):     60(ptr) Variable Function
   601(temp_rec):     29(ptr) Variable Function
      602(param):     60(ptr) Variable Function
      604(param):     11(ptr) Variable Function
      606(param):     54(ptr) Variable Function
      608(param):     54(ptr) Variable Function
      610(param):     29(ptr) Variable Function
                              Store 584(hit_anything) 392
             586:    8(float) Load 93(t_max)
                              Store 585(closest_so_far) 586
                              Store 587(i) 129
                              Branch 588
             588:             Label
                              LoopMerge 590 591 None
                              Branch 592
             592:             Label
             593:     18(int) Load 587(i)
             594:    101(ptr) AccessChain 90(self) 133
             595:     18(int) Load 594
             596:    27(bool) SLessThan 593 595
                              BranchConditional 596 589 590
             589:               Label
             598:     18(int)   Load 587(i)
             599:     60(ptr)   AccessChain 90(self) 129 598
             600:  15(Sphere)   Load 599
                                Store 597(o) 600
             603:  15(Sphere)   Load 597(o)
                                Store 602(param) 603
             605:     10(Ray)   Load 91(r)
                                Store 604(param) 605
             607:    8(float)   Load 92(t_min)
                                Store 606(param) 607
             609:    8(float)   Load 585(closest_so_far)
                                Store 608(param) 609
             611:    27(bool)   FunctionCall 73(Hit(struct-Sphere-vf3-f1-struct-Material-u1-u11-struct-Lambertian-vf311;struct-Ray-vf3-vf31;f1;f1;struct-HitRecord-vf3-vf3-f1-b1-struct-Material-u1-u11-struct-Lambertian-vf311;) 602(param) 604(param) 606(param) 608(param) 610(param)
             612:28(HitRecord)   Load 610(param)
                                Store 601(temp_rec) 612
                                SelectionMerge 614 None
                                BranchConditional 611 613 614
             613:                 Label
                                  Store 584(hit_anything) 411
             615:     54(ptr)     AccessChain 601(temp_rec) 157
             616:    8(float)     Load 615
                                  Store 585(closest_so_far) 616
             617:28(HitRecord)     Load 601(temp_rec)
                                  Store 94(rec) 617
                                  Branch 614
             614:               Label
                                Branch 591
             591:               Label
             618:     18(int)   Load 587(i)
             619:     18(int)   IAdd 618 133
                                Store 587(i) 619
                                Branch 588
             590:             Label
             620:    27(bool) Load 584(hit_anything)
                              ReturnValue 620
                              FunctionEnd
99(BackgroundColor(struct-Ray-vf3-vf31;):    9(fvec3) Function None 97
           98(r):     11(ptr) FunctionParameter
             100:             Label
        623(dir):     30(ptr) Variable Function
          626(t):     54(ptr) Variable Function
             624:     30(ptr) AccessChain 98(r) 133
             625:    9(fvec3) Load 624
                              Store 623(dir) 625
             627:     54(ptr) AccessChain 623(dir) 130
             628:    8(float) Load 627
             629:    8(float) FAdd 628 177
             630:    8(float) FMul 139 629
                              Store 626(t) 630
             633:    8(float) Load 626(t)
             634:    9(fvec3) CompositeConstruct 633 633 633
             635:    9(fvec3) ExtInst 1(GLSL.std.450) 46(FMix) 178 632 634
                              ReturnValue 635
                              FunctionEnd
106(WriteColor(i1;i1;vf3;):           2 Function None 102
          103(x):    101(ptr) FunctionParameter
          104(y):    101(ptr) FunctionParameter
      105(color):     30(ptr) FunctionParameter
             107:             Label
             638:    9(fvec3) Load 105(color)
             639:    9(fvec3) ExtInst 1(GLSL.std.450) 31(Sqrt) 638
                              Store 105(color) 639
             645:     18(int) Load 104(y)
             646:    257(ptr) AccessChain 243 129 134
             647:     18(int) Load 646
             648:     18(int) IMul 645 647
             649:     18(int) Load 103(x)
             650:     18(int) IAdd 648 649
             651:    9(fvec3) Load 105(color)
             652:    8(float) CompositeExtract 651 0
             653:    8(float) CompositeExtract 651 1
             654:    8(float) CompositeExtract 651 2
             655:  640(fvec4) CompositeConstruct 652 653 654 177
             657:    656(ptr) AccessChain 644(target) 129 650
                              Store 657 655
                              Return
                              FunctionEnd
109(xor_shift_rand():     12(int) Function None 108
             110:             Label
             660:     12(int) Load 659(state)
             662:     12(int) ShiftLeftLogical 660 661
             663:     12(int) Load 659(state)
             664:     12(int) BitwiseXor 663 662
                              Store 659(state) 664
             665:     12(int) Load 659(state)
             667:     12(int) ShiftRightLogical 665 666
             668:     12(int) Load 659(state)
             669:     12(int) BitwiseXor 668 667
                              Store 659(state) 669
             670:     12(int) Load 659(state)
             671:     12(int) ShiftLeftLogical 670 338
             672:     12(int) Load 659(state)
             673:     12(int) BitwiseXor 672 671
                              Store 659(state) 673
             674:     12(int) Load 659(state)
                              ReturnValue 674
                              FunctionEnd
116(Seed(vu2;vu2;):           2 Function None 113
114(screenCoord):    112(ptr) FunctionParameter
 115(screenSize):    112(ptr) FunctionParameter
             117:             Label
             677:    131(ptr) AccessChain 114(screenCoord) 134
             678:     12(int) Load 677
             679:    131(ptr) AccessChain 114(screenCoord) 130
             680:     12(int) Load 679
             681:    131(ptr) AccessChain 115(screenSize) 134
             682:     12(int) Load 681
             683:     12(int) IMul 680 682
             684:     12(int) IAdd 678 683
                              Store 659(state) 684
                              Return
                              FunctionEnd
      119(Rand():    8(float) Function None 118
             120:             Label
             685:     12(int) FunctionCall 109(xor_shift_rand()
             686:    8(float) ConvertUToF 685
             688:    8(float) FMul 686 687
                              ReturnValue 688
                              FunctionEnd
  123(RandVec2():  121(fvec2) Function None 122
             124:             Label
             691:    8(float) FunctionCall 119(Rand()
             692:    8(float) FunctionCall 119(Rand()
             693:  121(fvec2) CompositeConstruct 691 692
                              ReturnValue 693
                              FunctionEnd
  126(RandVec3():    9(fvec3) Function None 125
             127:             Label
             696:  121(fvec2) FunctionCall 123(RandVec2()
             697:    8(float) FunctionCall 119(Rand()
             698:    8(float) CompositeExtract 696 0
             699:    8(float) CompositeExtract 696 1
             700:    9(fvec3) CompositeConstruct 698 699 697
                              ReturnValue 700
                              FunctionEnd
